---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"
  workflow_dispatch

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: *.css
          tag_name: ${{ github.ref }}
          body: {{$steps.github_release.outputs.changelog}}